name: Daily Tech Digest
permissions:
  contents: write  # <-- Cette ligne est cruciale

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  update-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python fetch_article.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖 Daily article update - $(date +'%Y-%m-%d')"
