name: Daily Tech Digest

on:
  schedule:
    - cron: "0 7 * * *"  # Tous les jours à 7h UTC
  workflow_dispatch:     # Permet de lancer manuellement

jobs:
  update-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python fetch_article.py

      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "🤖 Daily article update" || echo "Nothing to commit"
          git push

